project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('simplemesh.urls')),
]

project/simplemesh/urls.py
from django.urls import path

from . import views

app_name = 'simplemesh'
urlpatterns = [
    # /
    path('', views.IndexView.as_view(), name='index'),

    # /1
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /message/1
    path('message/<int:pk>', views.MessageView.as_view(), name='message'),

    # /start [to start conversation]
    path('start/', views.start, name='start'),

    # /1/addmessage
    path('<int:conversation_id>/addmessage', views.add_message, name='add_message'),

    # /message/1/thought
    path('message/<int:message_id>/thought', views.add_thought, name='add_thought'),

    # /search/text%ssearch
    path('search/', views.search, name='search')
]

project/simplemesh/models.py
from django.db import models
from django.utils import timezone

class Conversation(models.Model):
    text = models.CharField(max_length=200)
    start_date = models.DateTimeField('start date')

    def __str__(self):
        return self.text

class Message(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date sent')
    def __str__(self):
        return self.text

class Thought(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date sent')
    def __str__(self):
        return self.text

project/simplemesh/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.utils import timezone
from django.urls import reverse
from django.views import generic

from .models import Conversation, Message

class IndexView(generic.ListView):
    template_name='simplemesh/index.html'
    context_object_name = 'results'

    def get_queryset(self):
        return Conversation.objects.order_by('start_date')

class DetailView(generic.DetailView):
    model = Conversation
    template_name = "simplemesh/detail.html"

class MessageView(generic.DetailView):
    model = Message
    template_name = 'simplemesh/message.html'

def start(request):
    if 'new' in request.POST:
        text = request.POST['new']
        time = timezone.now()
        c = Conversation(text=text, start_date=time)
        c.save()

    else:
        print("error, no text provided")
    return HttpResponseRedirect(reverse('simplemesh:index'))

def add_message(request, conversation_id):
    c = get_object_or_404(Conversation, pk=conversation_id)
    if 'new' in request.POST:    
        text = request.POST['new']
        time = timezone.now()
        c.message_set.create(text=text, pub_date=time)    

    return HttpResponseRedirect(reverse('simplemesh:detail',
    args=(conversation_id,)))

def add_thought(request, message_id):
    if 'new' in request.POST:
        m = get_object_or_404(Message, pk=message_id)
        text = request.POST['new']
        time = timezone.now()
        m.thought_set.create(text=text, pub_date=time)

    return HttpResponseRedirect(reverse('simplemesh:message',
    args=(message_id,)))

def search(request): 
    queried = "query" in request.POST
    query = request.POST['query'] if queried else ''
    object_type_input = request.POST['object_type'] if 'object_type' in request.POST else None
    object_type = Message if object_type_input == "Message" else Conversation
    no_results_text = "No results for your query." 
    errors = []
    result = None

    try:
        if query:
            result = object_type.objects.filter(text__icontains=query)
    
            if not result:
                errors.append(no_results_text)

    # TODO would be to create messaging and error handling

    except Exception as e:
        return HttpResponseRedirect(reverse('simplemesh:index'))

    context = {"type": object_type.__name__, 
        "errors": errors, "results": result}

    print(f"Queried: {queried}")
    return render(request, 'simplemesh/search.html', context)

project/simplemesh/templates/simplemesh/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Conversation #{{ conversation.id }}</title>
    </head>

    <body>

    <main>
    <breadcrumb>

    <a href="{% url 'simplemesh:index'%}">Return to Index</a>
    </breadcrumb>

    {% if conversation %}
        <h1><strong>Conversation #{{ conversation.id }}</strong></h1>
         {{ conversation.text }}
        
        <h2>Message Replies to Conversation #{{ conversation.id }}</h2>
        {% if conversation.message_set.all %}

            <ul>
            {% for m in conversation.message_set.all %}
            <li><strong>Message #{{ m.id }}:</strong> {{ m.text }} <em>@ {{ m.pub_date }}</em>
                <ul><li>
                    <a href="{% url 'simplemesh:message' m.id %}">
                Thoughts

                ({{ m.thought_set.count }})
                </a></li></ul></li>
            {% endfor %}
            </ul>

        {% else %}
        <p>No messages to be found for this conversation. Create one?</p>
        {% endif %}

        <h2>Add a Message</h2>
        <form action="{% url 'simplemesh:add_message' conversation.id %}" id="add_message" method="post">
        {% csrf_token %}
        <input type="text" name="new" id="new">
        <p><input type="submit" value="Submit" form="add_message"></p>

        </form>


        <h2>Search Messages (All Conversations)</h2>
        <form action="{% url 'simplemesh:search' %}" id="search" method="post">
        {% csrf_token %}
        <input type="text" name="query" id="query">
        <input type="hidden" name="object_type" id="object_type" value="Message">
        <p><input type="submit" value="Search" form="search"></p>
        </form>


    {% else %}
    <p>An error has occurred while trying to find Conversation #{{ conversation.id}}</p>
    </main>
    {% endif %}



    </body>
</html>

project/simplemesh/templates/simplemesh/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Recent Conversations</title>
    </head>

    <body>
    
    <h1>Conversations on Simplemesh</h1>
        {% if results %}
            <ul>
            {% for c in results %}
                <li><a href="{% url 'simplemesh:detail' c.id %}">
                    {{ c.text }}
                </a></li>
            {% endfor %}
            </ul>
        {% elif errors %}
            {{ errors }}
        {% endif %}
    <strong>Start a Conversation</strong>
    <form action="{% url 'simplemesh:start' %}" id="start_convo" method="post">
        {% csrf_token %}
        <input type="text" name="new" id="new">
        <p><input type="submit" value="Start" form="start_convo"></p>
    </form>


    <strong>Search Conversations</strong>
    <form action="{% url 'simplemesh:search' %}" id="search" method="post">
        {% csrf_token %}
        <input type="text" name="query" id="query">
        <p><input type="submit" value="Search Conversations" form="search"></p>
    </form>


    </body>

</html>

project/simplemesh/templates/simplemesh/message.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

    <body>
        <h1>Message #{{ message.id }} </h1>
    <breadcrumb><a href="{% url 'simplemesh:index' %}">Back to Index</a> |
        <a href="{% url 'simplemesh:detail' message.conversation.id %}">Back to Conversation</a> 
    </breadcrumb>
    {% if message %}
        <main>
        <p>{{ message.text }}</p>
        <em>@ {{ message.pub_date }}</em>
        <h2>Thoughts on Conversation #{{ message.conversation.id }} Message #{{ message.id }}</h2>

        {% if message.thought_set.all %}

            <ul>
            {% for t in message.thought_set.all %}
                <li><strong>Thought #{{ t.id }}:</strong>
                 {{ t.text }} <em>@ {{ t.pub_date }}</em>
            {% endfor %}

            </ul>
        {% else %}
            <p>No one has shared thoughts on this message.</p>

        {% endif %}



        <h2>Add your Thought</h2>

        <form action="{% url 'simplemesh:add_thought' message.id %}" id="add_thought" method="post">
        {% csrf_token %}
            <input type="text" name="new" id="new">
            <p><input type="submit" value="Submit" form="add_thought"></p>

    {% elif conversation %}

        <p>An error occurred while trying to find this message.</p>

        {% else %}
        <p>An error occurred while trying to find Conversation #{{ conversation.id }}.</p>
        </main>


    {% endif %}
    </body>
</html>

project/simplemesh/templates/simplemesh/search.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Search Results</title>
    </head>

    <body>
        <h1>Search Results</h1>
        <breadcrumb>
            <a href="{% url 'simplemesh:index' %}">Return to Index</a>
        </breadcrumb>

        {% if results %}
        <p>
            <ul>
            {% for c in results %}
            <li>
                {% if c.conversation.id %}
                <a href="{% url 'simplemesh:detail' c.conversation.id %}">
                    {{ c }}

                    (Link to Conversation #{{ c.conversation.id }})
                {% else %}
                <a href="{% url 'simplemesh:detail' c.id %}">{{ c }}</a>

                {% endif %}

                </a></li>
            {% endfor %}
            </ul>
        </p>
        {% else %}
            <p>Search your query below.</p>
        {% endif %}    
        
        {% if errors %}{% for e in errors %}
            <strong>{{ e }}</strong>
                {% endfor %}
        {% endif %}
    <form action="{% url 'simplemesh:search' %}" id="search" method="post">
        {% csrf_token %}
        <input type="text" name"query" id="query">
        <input type="hidden" name="object_type" id="object_type" value="Conversation">
        <p><input type="submit" value="Search Conversations" form="search"></p>
    </form>


    </body>

</html>